# Generated by Django 3.2 on 2021-10-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Time', models.DateTimeField(auto_now=True)),
                ('Like_count', models.IntegerField()),
                ('Comment', models.CharField(max_length=40)),
                ('Post_data', models.CharField(max_length=80)),
            ],
        ),
    ]
