# Generated by Django 3.2 on 2021-11-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FriendId', models.IntegerField()),
                ('FuserId', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('Friends_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
